blog/urls.py
from django.urls import path
from .views import blog, blog_details


app_name = "blog"

urlpatterns = [
    path("", blog, name="blog"),
    path("category/<str:category>", blog, name="blog-category"),
    path("blog-details/<int:id>", blog_details, name="blog-details"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
    path("blog/", include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, documents_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documents_root = settings.STATIC_ROOT)

root/urls.py
from django.urls import path
from .views import home, portfolio_details, service_details


app_name = "root"

urlpatterns = [
    path("", home, name="home"),
    path("portfolio-details", portfolio_details, name="portfolio-details"),
    path("service-details", service_details, name="service-details"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CategoryBlog(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blog", default="default.jpg")
    category = models.ManyToManyField(CategoryBlog)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

root/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Blog
# Create your views here.

def blog(request, category=None):
    if category is not None:
        blog = Blog.objects.filter(category__title=category)
        
    else:
        blog = Blog.objects.all()
        
    blog_paginate = Paginator(blog, 2)
    first_page = 1
    last_page = blog_paginate.num_pages

    try:
        page_number = request.GET.get("page")
        blog = blog_paginate.get_page(page_number)
    except:
        page_number = first_page
        blog = blog_paginate.get_page(first_page)
    
    context = {
        "blogs":blog,
        "first" : first_page,
        "last" : last_page
    }


    return render(request, 'blog/blog.html', context=context)    









def blog_details(request, id):
    #id = request.GET.get("id")
    blog = get_object_or_404(Blog, id=id)
    contex = {
        'blog':blog,
    }
    return render(request, 'blog/blog-details.html', context=contex)

root/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'root/index.html')

def portfolio_details(request):
    return render(request, 'root/portfolio-details.html')

def service_details(request):
    return render(request, 'root/service-details.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block 'title' %}     {% endblock 'title' %}</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/animate.css/animate.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Main CSS File -->
  <link href={% static "assets/css/main.css" %} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Selecao
  * Template URL: https://bootstrapmade.com/selecao-bootstrap-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src={% static "assets/img/logo.png" %} alt=""> -->
        <h1 class="sitename">Selecao</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href={% url "root:home"%} class="active">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li>
          <li><a href={% url "blog:blog" %}>Blog</a></li>
          <li class="dropdown"><a href="#"><span>Category</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              {% for category in categories %}
              <li><a href={% url "blog:blog-category" category=category.title %}>{{category.title}}</a></li>
              {% endfor %}

              {% comment %} <li><a href="#">Dropdown 2</a></li>
              <li><a href="#">Dropdown 3</a></li>
              <li><a href="#">Dropdown 4</a></li> {% endcomment %}
            </ul>
          </li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>
  {% block 'content' %}



  {% endblock 'content' %}
  
  <footer id="footer" class="footer dark-background">
    <div class="container">
      <h3 class="sitename">Selecao</h3>
      <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
      <div class="social-links d-flex justify-content-center">
        <a href=""><i class="bi bi-twitter-x"></i></a>
        <a href=""><i class="bi bi-facebook"></i></a>
        <a href=""><i class="bi bi-instagram"></i></a>
        <a href=""><i class="bi bi-skype"></i></a>
        <a href=""><i class="bi bi-linkedin"></i></a>
      </div>
      <div class="container">
        <div class="copyright">
          <span>Copyright</span> <strong class="px-1 sitename">Selecao</strong> <span>All Rights Reserved</span>
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you've purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </div>
  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/php-email-form/validate.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/imagesloaded/imagesloaded.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>

  <!-- Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

</body>

</html>

templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}blog{% endblock 'title' %}
{% block 'content' %}
  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container position-relative">
        <h1>Blog</h1>
        <p>Esse dolorum voluptatum ullam est sint nemo et est ipsa porro placeat quibusdam quia assumenda numquam molestias.</p>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Blog</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Blog Posts Section -->
    <section id="blog-posts" class="blog-posts section">
      {% for blog in blogs %}
      <div class="container">
        <div class="row gy-4">

          <div class="col-lg-4">
            <article>

              <div class="post-img">
                <img src={{blog.default.url}} alt="" class="img-fluid">
              </div>

              <p class="post-category">{{blog.category.title}}</p>

              <h2 class="title">
                <a href={% url 'blog:blog-details' id=blog.id%}>title</a>
              </h2>

              <div class="d-flex align-items-center">
                <img src={% static "assets/img/blog/blog-author.jpg" %} alt="" class="img-fluid post-author-img flex-shrink-0">
                <div class="post-meta">
                  <p class="post-author">{{blog.user.username}}</p>
                  <p class="post-date">
                    <time datetime="2022-01-01">Jan 1, 2022</time>
                  </p>
                </div>
              </div>

            </article>
          </div>
          {% endfor %}
          <!-- End post list item -->

          {% comment %} <div class="col-lg-4">
            <article>

              <div class="post-img">
                <img src={% static "assets/img/blog/blog-2.jpg" %} alt="" class="img-fluid">
              </div>

              <p class="post-category">Sports</p>

              <h2 class="title">
                <a href="blog-details.html">Nisi magni odit consequatur autem nulla dolorem</a>
              </h2>

              <div class="d-flex align-items-center">
                <img src={% static "assets/img/blog/blog-author-2.jpg" %} alt="" class="img-fluid post-author-img flex-shrink-0">
                <div class="post-meta">
                  <p class="post-author">Allisa Mayer</p>
                  <p class="post-date">
                    <time datetime="2022-01-01">Jun 5, 2022</time>
                  </p>
                </div>
              </div>

            </article>
          </div><!-- End post list item -->{% endcomment %}

        </div>
      </div>

    </section><!-- /Blog Posts Section -->

    <!-- Blog Pagination Section -->
    <section id="blog-pagination" class="blog-pagination section">

      <div class="container">
        <div class="d-flex justify-content-center">
          <ul>
            
            {% comment %}<li><a href="#"><i class="bi bi-chevron-left"></i></a></li>{% endcomment %}
             {% if blogs.has_next and blogs.has_previous %} 
            


              <a href={% url 'blog:blog' %}?page={{first}}><button>first page</button>
              <a href={% url 'blog:blog' %}?page={{blogs.previous_page_number}}><button>prev pag</button>
              <a href={% url 'blog:blog' %}?page={{blogs.next_page_number}}><button>next page</button>
              <a href={% url 'blog:blog' %}?page={{last}}><button>last page</button>

            
            {% elif blogs.has_next %}
              <a href={% url 'blog:blog' %}?page={{blogs.next_page_number}}><button>next page</button>
              <a href={% url 'blog:blog' %}?page={{last}}><button>last page</button>
            {% elif blogs.has_previous %}
              <a href={% url 'blog:blog' %}?page={{first}}><button>first page</button>
              <a href={% url 'blog:blog' %}?page={{blogs.previous_page_number}}><button>prev page</button>
            {% endif %} 
            

             {% comment %}<li><a href="#"><i class="bi bi-chevron-right"></i></a></li> {% endcomment %}
             
          </ul>
        </div>
      </div>

    </section><!-- /Blog Pagination Section -->

  </main>
  {% endblock 'content' %}

templates/root/portfolio-details.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}portfolio-details{% endblock 'title' %}
{% block 'content' %}



  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container position-relative">
        <h1>Portfolio Details</h1>
        <p>Esse dolorum voluptatum ullam est sint nemo et est ipsa porro placeat quibusdam quia assumenda numquam molestias.</p>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Portfolio Details</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Portfolio Details Section -->
    <section id="portfolio-details" class="portfolio-details section">

      <div class="container" data-aos="fade-up">

        <div class="portfolio-details-slider swiper init-swiper">
          <script type="application/json" class="swiper-config">
            {
              "loop": true,
              "speed": 600,
              "autoplay": {
                "delay": 5000
              },
              "slidesPerView": "auto",
              "navigation": {
                "nextEl": ".swiper-button-next",
                "prevEl": ".swiper-button-prev"
              },
              "pagination": {
                "el": ".swiper-pagination",
                "type": "bullets",
                "clickable": true
              }
            }
          </script>
          <div class="swiper-wrapper align-items-center">

            <div class="swiper-slide">
              <img src={% static "assets/img/portfolio/app-1.jpg" %} alt="">
            </div>

            <div class="swiper-slide">
              <img src={% static "assets/img/portfolio/product-1.jpg" %} alt="">
            </div>

            <div class="swiper-slide">
              <img src={% static "assets/img/portfolio/branding-1.jpg" %} alt="">
            </div>

            <div class="swiper-slide">
              <img src={% static "assets/img/portfolio/books-1.jpg" %} alt="">
            </div>

          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
          <div class="swiper-pagination"></div>
        </div>

        <div class="row justify-content-between gy-4 mt-4">

          <div class="col-lg-8" data-aos="fade-up">
            <div class="portfolio-description">
              <h2>This is an example of portfolio details</h2>
              <p>
                Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.
              </p>
              <p>
                Amet consequatur qui dolore veniam voluptatem voluptatem sit. Non aspernatur atque natus ut cum nam et. Praesentium error dolores rerum minus sequi quia veritatis eum. Eos et doloribus doloremque nesciunt molestiae laboriosam.
              </p>

              <div class="testimonial-item">
                <p>
                  <i class="bi bi-quote quote-icon-left"></i>
                  <span>Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.</span>
                  <i class="bi bi-quote quote-icon-right"></i>
                </p>
                <div>
                  <img src={% static "assets/img/testimonials/testimonials-2.jpg" %} class="testimonial-img" alt="">
                  <h3>Sara Wilsson</h3>
                  <h4>Designer</h4>
                </div>
              </div>

              <p>
                Impedit ipsum quae et aliquid doloribus et voluptatem quasi. Perspiciatis occaecati earum et magnam animi. Quibusdam non qui ea vitae suscipit vitae sunt. Repudiandae incidunt cumque minus deserunt assumenda tempore. Delectus voluptas necessitatibus est.
              </p>

              <p>
                Sunt voluptatum sapiente facilis quo odio aut ipsum repellat debitis. Molestiae et autem libero. Explicabo et quod necessitatibus similique quis dolor eum. Numquam eaque praesentium rem et qui nesciunt.
              </p>

            </div>
          </div>

          <div class="col-lg-3" data-aos="fade-up" data-aos-delay="100">
            <div class="portfolio-info">
              <h3>Project information</h3>
              <ul>
                <li><strong>Category</strong> Web design</li>
                <li><strong>Client</strong> ASU Company</li>
                <li><strong>Project date</strong> 01 March, 2020</li>
                <li><strong>Project URL</strong> <a href="#">www.example.com</a></li>
                <li><a href="#" class="btn-visit align-self-start">Visit Website</a></li>
              </ul>
            </div>
          </div>

        </div>

      </div>

    </section><!-- /Portfolio Details Section -->

  </main>
{% endblock 'content' %}

templates/root/service-details.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}service-details{% endblock 'title' %}
{% block 'content' %}
  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container position-relative">
        <h1>Service Details</h1>
        <p>Esse dolorum voluptatum ullam est sint nemo et est ipsa porro placeat quibusdam quia assumenda numquam molestias.</p>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Service Details</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Service Details Section -->
    <section id="service-details" class="service-details section">

      <div class="container">

        <div class="row gy-5">

          <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">

            <div class="service-box">
              <h4>Serices List</h4>
              <div class="services-list">
                <a href="#" class="active"><i class="bi bi-arrow-right-circle"></i><span>Web Design</span></a>
                <a href="#"><i class="bi bi-arrow-right-circle"></i><span>Web Design</span></a>
                <a href="#"><i class="bi bi-arrow-right-circle"></i><span>Product Management</span></a>
                <a href="#"><i class="bi bi-arrow-right-circle"></i><span>Graphic Design</span></a>
                <a href="#"><i class="bi bi-arrow-right-circle"></i><span>Marketing</span></a>
              </div>
            </div><!-- End Services List -->

            <div class="service-box">
              <h4>Download Catalog</h4>
              <div class="download-catalog">
                <a href="#"><i class="bi bi-filetype-pdf"></i><span>Catalog PDF</span></a>
                <a href="#"><i class="bi bi-file-earmark-word"></i><span>Catalog DOC</span></a>
              </div>
            </div><!-- End Services List -->

            <div class="help-box d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-headset help-icon"></i>
              <h4>Have a Question?</h4>
              <p class="d-flex align-items-center mt-2 mb-0"><i class="bi bi-telephone me-2"></i> <span>+1 5589 55488 55</span></p>
              <p class="d-flex align-items-center mt-1 mb-0"><i class="bi bi-envelope me-2"></i> <a href="mailto:contact@example.com">contact@example.com</a></p>
            </div>

          </div>

          <div class="col-lg-8 ps-lg-5" data-aos="fade-up" data-aos-delay="200">
            <img src={% static "assets/img/services.jpg" %} alt="" class="img-fluid services-img">
            <h3>Temporibus et in vero dicta aut eius lidero plastis trand lined voluptas dolorem ut voluptas</h3>
            <p>
              Blanditiis voluptate odit ex error ea sed officiis deserunt. Cupiditate non consequatur et doloremque consequuntur. Accusantium labore reprehenderit error temporibus saepe perferendis fuga doloribus vero. Qui omnis quo sit. Dolorem architecto eum et quos deleniti officia qui.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> <span>Aut eum totam accusantium voluptatem.</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Assumenda et porro nisi nihil nesciunt voluptatibus.</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Ullamco laboris nisi ut aliquip ex ea</span></li>
            </ul>
            <p>
              Est reprehenderit voluptatem necessitatibus asperiores neque sed ea illo. Deleniti quam sequi optio iste veniam repellat odit. Aut pariatur itaque nesciunt fuga.
            </p>
            <p>
              Sunt rem odit accusantium omnis perspiciatis officia. Laboriosam aut consequuntur recusandae mollitia doloremque est architecto cupiditate ullam. Quia est ut occaecati fuga. Distinctio ex repellendus eveniet velit sint quia sapiente cumque. Et ipsa perferendis ut nihil. Laboriosam vel voluptates tenetur nostrum. Eaque iusto cupiditate et totam et quia dolorum in. Sunt molestiae ipsum at consequatur vero. Architecto ut pariatur autem ad non cumque nesciunt qui maxime. Sunt eum quia impedit dolore alias explicabo ea.
            </p>
          </div>

        </div>

      </div>

    </section><!-- /Service Details Section -->

  </main>
  {% endblock 'content' %}